### ISSUE TITLE
Broke page character encoding

### ISSUE THREAD

**Issue by ghost** [Pomax/Usered#3]
After every login or log off it breaks character encoding (utf-8 with Central European characters): I was searching if it somehow change webpage encoding but it is still utf-8 so I have no clue what is wrong here, cos after I manually refresh the site everything is as it should be - any ideas?
- now I noticed it basically broke the encoding with ANY CLICK ON THE "log in" BUTTON - even if I enter wrong values (name/pass) and hit "log in" as soon as it gives the error message all is f****d up again, what...?!

**Comment by Pomax** [comment]
I'm a little confused, what's "utf-8 with Central European characters"? UTF-8 has no qualifications, it's simply a byte encoding for all code points assigned in Unicode.

That said, the code doesn't do any page-modifications, the only thing it touches is the `$_SESSION` handler in https://github.com/Pomax/Usered/blob/master/user.php#L401-L406. Are you calling it as API via Javascript (live updates), or are you using it as embedded PHP (page-loading)?

**Comment by ghost** [comment]
I was only further detailing the case, that is that only CE letters are affected, nothing else + without your script everything is absolutely fine...and as i said it is fine with your script too but only after manual refresh of the page which is strange, isn't it?

I am probably not that experienced as I do not understand you enough what exactly do you mean by "API via JavaScrip[t" or "embedded PHP" cos I am using both cos it does not work without the .js part as I understand it...or did you mean something else?

Or maybe you are asing me if I am using it for application or "normal" webpage? In that case I am using it in PHP webpages...

**Comment by Pomax** [comment]
Pretty much. 

Yeah that's very weird. The only parts that do anything with HTML is https://github.com/Pomax/Usered/blob/master/js/user.js#L176-L219, but that doesn't change anything about the page charset, it just builds a form element for the login/logout. 

(on a complete sidenote, I hope you saw https://github.com/Pomax/Usered/blob/master/js/user.js#L82 and gave that a meaningful implementation?)

**Comment by ghost** [comment]
Actually that link you gave is not an issue as what i am doing is only implementing content text editor using predefined user/password pairs (basically just one user - owner of the page), so really the only thing that bugs me is that page encoding "glitch", I am helpless.

**Comment by Pomax** [comment]
Just to make sure, is your page using proper HTML? No matter whatever else, does it look like this:

```
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>...</title>
    ...
  </head>
  <body>
    ...
  </body>
</html>
```

Because both the HTML5 doctype syntax, and meta element, are crucial. If your HTML doesn't look like this, make sure it does. That might solve the problem immediately.

**Comment by ghost** [comment]
:-D Ehm, yea, it surely looks like that...maybe I introduced myself not good enough (sorry my english sux, I know) so I will try once more: altho I did not get what you were asking right away I guess I am quite advanced webdesigner with 17+ years of experience mostly with Macromedia Flash ActionScript 2 and later PHP/jQuery (tho not that experienced as I was for years with the FLASH), so such basics of HTML are know to me very well, no problem. ;-)

**Comment by Pomax** [comment]
plenty of people who use dreamweaver and php a lot seem to not understand why `<!doctype html>` would matter, or why the meta tag is necessary "when their browser shows things fine without it", though =) Always cover the basics.

are there any DOM changes to the head when you use the login/logout buttons? (does the meta charset change?) Also, does the browser's encoding switch? (what is it before pressing a button -hopefully utf8- and what does it claim after?). Also, is this in all browsers or in a specific one?

**Comment by ghost** [comment]
No, there are absolutely no changes to DOM elements whatsoever, I also removed action part from your script as I need to stay where it is :)

You know what? Being so many years in webdesign I always and I mean ALWAYS try several browsers when I have some probs with scripts exactly for the reason you are trying to find out by asking me but for some strange reason in this case I BROKE MY OWN RULES thus not testing it anywhere except my belowed Firefox :-D ...and voila, when tested on Chrome IT WORKS AS IT SHOULD so it is something specific to Mozilla Firefox (v40+)...the thing is I as a webdesigner am using many extensions so it might be some of them is causing the problem: I will disabling one by one and then let you know so you can tell all possible users of your script which extension for Firefox they need to avoid in case they have the same probs as me. ;-)

In case all extensions are disabled BUT still getting this strange behavior I am affraid it'll be something built into FF... :-(

**Comment by ghost** [comment]
TESTED:
Unfortunately, it is something specific to FF cos I downloaded "pure" FF v43 + I even disabled all plugins like Flash, JAVA etc. (there were 3 actually) BUT it still do the same lame thing, I hate it to say but ppl at Mozilla got fucked up, really it sucks big time! :-(

On the side note: I noticed login does not work by simply clicking on ENTER key - why? Can it be set up somewhere in your script?

**Comment by Pomax** [comment]
hm, silly question perhaps, but do you have all reporting turned on in the firefox dev tools console (both warnings and errors for all categories)? I wonder if we're missing something going wrong during network activity. Is this a publically accessible URL?

**Comment by ghost** [comment]
Actually I am using Firebug and yes, CONSOLE is set to ALL...no problems indicated at all.
Unfortunately that project is not publicly accessible, it is still in very initial stages running purely here on local server.

**Comment by Pomax** [comment]
hm, does it also screw up with just the JS? i.e. if you don't even bother having the PHP file on the server (so the JS will fail when it tries to post to the page, but whatever). Because if so, that would be a easy thing to try in a jsbin, if it really is firefox doing weird things. Then we can just file a bug on the mozilla bug tracker.

**Comment by ghost** [comment]
I am not sure if I understood you right once again, but I did this: I removed the PHP part and let just those 2 .js files intact (included via script tags in head section) and after I tried to log in it made the same glitch with the encoding although I wa snot log in, of course, so I guess you can go to file a bug on the mozilla.org tracker.

**Comment by Pomax** [comment]
Hm, I'm trying to reproduce this with just `user.js` without the PHP backing but I just can't seem to make this happen. Can you create a jsbin.com or something that reproduces this bug for you? I'd like to see if I even see the same thing happening. (can't file a bug without proof there is one, or even steps to reproduce it, after all)

**Comment by ghost** [comment]
how to?

**Comment by ghost** [comment]
I have probs with internet connection today (should be solved tomorrow evening) and then I will upload the projet as it is temporarily for you to my public FTP server, give you the link and you can test it yourself...just wait until tomorrow evening, OK? Everything here is extremelly slow now, like 32 kbps from normal 1000 kbps (10 MBit link) - most probably my antena is "kaput"!!! :-(

**Comment by Pomax** [comment]
Hm, simplest might be to just open the page you have right now in a browser, and because it doesn't rely on PHP, simply go file -> save, and make the browser save it to disk. Then open that in an editor, remove the bits that don't contribute to, or show off, the problem, and then you can maybe upload it somewhere, or even add it here as a comment with code?

**Comment by ghost** [comment]
No, that does not work that way: if I do that the webpage looks completely different - there is basically nothing there, my pages are way too complicated to make it in such a simple way as you propose, sorry + anyway I tried that and as for the encoding mish-mash there was no problem at all but once again as I said it has almosst nothing to do with the process my web is generated, so you cannot take it as a prove of anything. I will simply have to upload it tomorrow as I said earlier, there seem to be no other way around to show you that behavior...

**Comment by ghost** [comment]
http://pemino.pemino.sk/php/a1.php
Just put there any random name and pass and see for example menu how it changes partialy into some nonsensical characters...then just CLICK SOME OTHER MENU and voila, everything is encoded as it should once again - and this is happening only on Firefox, not on Chrome (other browsers not tested)

**Comment by Pomax** [comment]
wait, this is XHTML1.0... why is it XHTML1.0 (not even 1.1) instead of HTML5? Also, I don't see a meta tag that tells the browser the actual charset, so this is certainly weird, but first off your site needs a meta tag for the content charset. In HTML5, that'd be `<meta charset="utf-8">`, in XHTML it'd be `<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>`, so let's start there. Add a charset to your page, make sure it's the very first element in the `<head>` block, so that it doesn't trigger a significant DOM reparse, and let's see if that fixes it.

**Comment by ghost** [comment]
Pomax, I do not know how you are looking at the source code of my page (I am usinf Firebug FF extension, try that one, please) but there definitely is charset metatag (this is from Firebug, just the charset line in head: `<meta content="text/html; charset=utf-8" http-equiv="Content-type">`) - look better, please. As for the XHMTL1.0 - I am reusing my older scripts from times when I was doing completely flash websites (that is adobe flash and nothing else, basically) and those were required then and as those did not make any  bad/wrong/mulfunctioning stuff with my new approach (php/js/jquery/xml) I let them be there - I never had any probs with that (until now).

**Comment by Pomax** [comment]
Ah, my apologies, it gets appended weirdly: [view-source:http://pemino.pemino.sk/php/a1.php](view-source:http://pemino.pemino.sk/php/a1.php) so it looks like there's only one meta element when there are two. It's also not the first element in the `<head>`, so you still need to move it to rule out encoding-change timing issues.

As for XHTML1.0, it might be convenient, but it's also a web technology from 15 years ago with minor differences from real HTML, so at this point in time it's not really a good idea to stick to it for modern browsers. I'd strongly advise you to move this over to modern HTML5 format instead. However, if you don't want to for whatever reason, then some more work is still necessary before this is a reducible problem:

Your login button seems to do a full page refresh, and the server doesn't send a header that indicates the content-type encoding, so it might be worth [updating the nginx conf](http://serverfault.com/questions/312177/how-to-enable-correct-charset-http-header-in-nginx) and seeing if that makes reloads based on login stable.

**Comment by ghost** [comment]
It is appended/created in runtime by browser cos in PHP scripts it is sequenced rightly as it should be + as of header tags it doe snot matter in what sequence it is rendered actually. Where do you see one meta tag being actually two??? There is no such thing, 100%.

As for the XHTML: as I said above it is just the part from code I was using thru the years without any problem so there was no need changing it but in principle I have no problem changing it to something different if it will helps us in our problem.

As for the login fullpage refresh: it does not matter - I removed action attribut from the form cos I did not need to redirect it to any script - I wanted to stay at the page useer actually is, but as I had similar thoughts as you have now I added action so it would actualy open another subpage (menu button, like a2.php, or a7.php, whatever) and it still looks the same mish-mash as you see now.

OK, I will look into that nginx stuff and let you know then...

**Comment by ghost** [comment]
BTW I just realize I have no clue what the hell is NGINX - I have never heard of. From what I found on Google it is just some server type - if so: I have no clue/access of setting any preferences for server except in php.ini for PHP v5.3 (I even do not know if my public server is NGINX at all) - can you tell me more, please?

**Comment by ghost** [comment]
PROBLEM SOLVED! :-)
I just enabled (as it was commented out by default) -  inspired by your NGINX stuff - line `default_charset = "utf-8"` in my php.ini file, so now it works correctly as it should, thanx for inspiration! ;-)

**Comment by Pomax** [comment]
Nice!

Yeah, that would have been the next step: make the server daemon generate content as utf8, then make PHP make sure to be set to utf8, then make sure the file itself is saved _as_ utf8, make sure any database it's using has tables set to utf8 datatypes, make the html file explciitly say it's charset is utf8 (and yes, the order actually matters for the charset tag, because when the browser sees that tag, it stops whatever it's doing, changes its charset decode, and then reparses the entire document, so the later in the <head> it is, the longer the page will take. Especially if it's after <script> elements that can become a noticable problem). UTF8 all the way can be quite tricky.

(Also I mentioned nginx because if you look at the network respoonse for a1.php, the headers will show you that it's being routed through an nginx server, and sometimes those are not explicitly set to treat data as UTF8 unless specifically overruled)

**Comment by ghost** [comment]
Yes, it is understood that I of course had all of that EXCEPT the php.ini part which I found out just while ago as I wrote it to you earlier.

And as for the sequencing/ordering tags inside HEAD: as I also said earlier I HAVE IT SEQUENCED RIGHT IN MY PHP FILES, that is: my charset metatag is the first one right after head tag, BUT for some reason it is parsed/created in random sequence HENCE it is actually not important for a browser inside head tag I guess.

Anyway, problem solved, so once again thanx a lot for your help and for the great script too, of course!

**Comment by Pomax** [comment]
that logic doesn't hold. If you have it in the right place in your PHP, and it's getting generated "not in that place" by the deploy system, then that's a potential bug in your deploy sytem. That "hence" is not a logical conclusion in the slightest: just because you don't notice it affecting page render speed (because all it's redoing is a few opengraph elements) doesn't mean the browser's not wasting cycles on that. Anyway, good to know it's solved.
